apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-portal
  namespace: kubevirt-portal
  labels:
    app: kubevirt-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-portal
  template:
    metadata:
      labels:
        app: kubevirt-portal
    spec:
      serviceAccountName: vm-manager-serviceaccount
      containers:
      - name: kubevirt-portal
        image: ghcr.io/michaeltrip/kubevirt-portal:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: kubevirt-portal-config
        - secretRef:
            name: kubevirt-portal-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
