apiVersion: v1
kind: Service
metadata:
  name: kubevirt-portal
  namespace: kubevirt-portal
spec:
  selector:
    app: kubevirt-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
